### ISSUE TITLE
Task2 potential issues

### ISSUE THREAD

**Issue by ghost** [Coursework-II-The-Prototype/bill_spliting_system#7]
### insert method:
 - [x] What should happen when the user insert a new item that exists in the order already?
   - overwrite:
     - current: {id: 1, amount: 2}
     - new:     {id: 1, amount: 1}
     - after:   {id: 1, amount: 1}
   - increment:
     - current: {id: 1, amount: 2}
     - new:     {id: 1, amount: 1}
     - after:   {id: 1, amount: 3}

Choose one of the above.

### update method:
 - [x] When a item with the same `item_id` exists in both public and personal order under the same `user_id`, the user cannot choose which one to edit freely. The user should be able to select the item by an index. E.g.:
 index | name | price | amount | isPublic
==========================================
 0 | item_A | $1 | 1 | true
 1 | item_A | $1 | 2 | false
 2 | item_B | $2 | 1 | false
 - [x] Unify order when `isPublic` is changed and there is an existing order.
 - [x] When a user does not have any item, should the update command be available?
 - [x] Optional: display a table for what the user can edit?

**Comment by ghost** [comment]
Please create a new branch for this issue.

**Comment by YidingWang05** [comment]
Hello, I chose to take the increment method for the `insert` function. But for public items, if two users separately added the same item, there will still be two information about this method. 
e.g:
{"item_id": "22", "quantity": 1, "isPublic": true, "user_id": "user1"}
{"item_id": "22", "quantity": 3, "isPublic": true, "user_id": "user2"}
I believe, by doing this, can enable users to have a clear view of who added what.

For `update` method, I planned to check both public and personal order lists then if the items exsist in both lits and under the same `user_id`, this method should ask the user which they want to modify. I believe this will make our CLI more accessible to the users. Furthermore, I will enable this method to remove item from order lists if user input `0` for new quantity they want.

I almost finish everything, I'll have some basic tests by myself. If everything ok, I will push it by tomorrow afternoon.

**Comment by YidingWang05** [comment]
I found another potential problem. If we have the following situation:
e.g.
{"item_id": "22", "quantity": 1, "isPublic": true, "user_id": "user1"}
{"item_id": "22", "quantity": 3, "isPublic": false, "user_id": "user1"}
user1 wants to change `isPublic` into false, order db will become:
{"item_id": "22", "quantity": 1, "isPublic": false, "user_id": "user1"}
{"item_id": "22", "quantity": 3, "isPublic": false, "user_id": "user1"}

Therefore, I need some extra time to deal with this problem.  I plan to do an increment, just like what we discussed for `insert`, for this circumstance.

After modifying, the outcome of this situation should be:
{"item_id": "22", "quantity": 4, "isPublic": false, "user_id": "user1"}

Sorry for the delay, but I could still finish it by the evening of today.

**Comment by ghost** [comment]
Indeed. Good one.

**Comment by YidingWang05** [comment]
Hi, for this question:
When a user does not have any item, should the update command be available?
I believe it will be better to do a check on order db when the users want to call the `update` method. 

I have finished updating and a few basic manual checks.  Now it's ready for the unit tests if required.

**Comment by ghost** [comment]
I have pushed the unit tests and rebased the branch on main. Pull it if you need to make any changes, otherwise it is ready for merge and please make a pull request.
